import Header from 'components/ui/Header/Header'
import Footer from 'components/ui/Footer/Footer'
import { ReactElement } from 'react'
import Head from 'next/head'

export default function Layout (props: {
  children: ReactElement | null | undefined
}) {
  return (
    <>
      <Head>
        <title>Mon zoo mobile</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <div className='container'>{props.children}</div>
      <Footer />
    </>
  )
}
