import classes from './Header.module.css'
import Nav from 'components/ui/Nav/Nav'
import Head from 'next/head'

export default function Header () {
  return (
    <>
      <Head>
        <title>Mon zoo à moi</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header className={classes.Header}>
        <div
          className='container'
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center'
          }}
        >
          <h1 style={{ margin: 0 }}>Mon Zoo à moi !</h1>
          <Nav />
        </div>
      </header>
    </>
  )
}
